INSERT INTO BIBLIOTECA (CODIGO_BIBLIOTECA, NOME, CODIGO_CIDADE, ESTADO) VALUES (10,'Biblioteca Carolina',1,'SP');
INSERT INTO BIBLIOTECA (CODIGO_BIBLIOTECA, NOME, CODIGO_CIDADE, ESTADO) VALUES (20,'Biblioteca Djamila',2,'SP');
INSERT INTO BIBLIOTECA (CODIGO_BIBLIOTECA, NOME, CODIGO_CIDADE, ESTADO) VALUES (30,'Biblioteca Conceicao',3,'SP');

INSERT INTO CIDADE (CODIGO_CIDADE, NOME_CIDADE, ESTADO) VALUES (1,'Cotia','SP');
INSERT INTO CIDADE (CODIGO_CIDADE, NOME_CIDADE, ESTADO) VALUES (2,'Itapevi','SP');
INSERT INTO CIDADE (CODIGO_CIDADE, NOME_CIDADE, ESTADO) VALUES (3,'Sao Paulo','SP');